# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
---
# docker compose up --detach
# docker compose down
services:
  clickhouse:
    image: clickhouse/clickhouse-server:26.5.1
    ports: ["8123:8123"]
    environment:
      CLICKHOUSE_PASSWORD: Test@12345
      CLICKHOUSE_USER: default

  # Navigate to the web console at: http://localhost:4200
  # ...or connect with a PostgreSQL client to port 6432 using:
  #     - username: crate
  #     - password: crate
  cratedb:
    image: crate:6.3.5
    ports: ["4200:4200", "6432:5432"]

  mssql:
    image: mcr.microsoft.com/mssql/server:2025-CU5-ubuntu-24.04
    ports: ["1433:1433"]
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      # Username: SA
      SA_PASSWORD: Test@12345

  mysql:
    image: mysql:8.4.2
    ports: ["3306:3306"]
    environment:
      # Username: root
      MYSQL_ROOT_PASSWORD: Test@12345

  oracle:
    image: container-registry.oracle.com/database/free:23.26.2.0-lite
    ports: ["1521:1521"]
    environment:
      # SID: FREE
      # Username: SYSTEM
      ORACLE_PWD: Test@12345

  postgres:
    image: postgres:18.4
    ports: ["5432:5432"]
    environment:
      POSTGRES_PASSWORD: Test@12345
      POSTGRES_USER: postgres

  # Navigate to the web console at: http://localhost:9000
  # ...or connect with a PostgreSQL client to port 8812 using:
  #     - username: admin
  #     - password: quest
  questdb:
    image: questdb/questdb:9.4.3
    ports:
      - "9000:9000"  # REST API and Web Console
      - "9009:9009"  # InfluxDB line protocol
      - "8812:8812"  # Postgres wire protocol
      - "9003:9003"  # Min health server

  snowflake:  # mock Snowflake server, not working in PyCharm yet
    image: ghcr.io/tekumara/fakesnow:0.11.9
    ports: ["64616:64616"]

  # Create and format the data file before launching the server:
  #
  #     docker run \
  #       --security-opt seccomp=unconfined \
  #       --volume $(pwd)/data/tigerbeetle:/data \
  #       ghcr.io/tigerbeetle/tigerbeetle \
  #       format \
  #         --replica-count=1 \
  #         --replica=0 \
  #         --cluster=0 \
  #         /data/0_0.tigerbeetle
  tigerbeetle:
    image: ghcr.io/tigerbeetle/tigerbeetle
    command: "start --addresses=0.0.0.0:3000 /data/0_0.tigerbeetle"
    security_opt: ["seccomp=unconfined"]
    ports: ["3000:3000"]
    volumes: ["./data/tigerbeetle:/data"]

  trino:
    # Username: admin
    # Password is null
    image: trinodb/trino:481
    ports: ["8080:8080"]
